Feat/main page
rrrds/airbnb-demo-frontend pull request #1
Opened 2018-01-03 08:25 UTC by rrrds

Что готово:
- **Header**
- **Explore** block

2018-01-04 12:03 UTC, evgenyrodionov commented
Я не проверяю не готовое — смысл от 10% страницы? Как её мерджить, если нет замечаний?

2018-01-05 09:12 UTC, rrrds commented
Desktop version of amin page

2018-01-06 15:42 UTC, imevro requested changes
читай частые ошибки, тупо оттуда собрал почти всё

2018-01-06 15:42 UTC, evgenyrodionov commented on src/Destinations/Card.js
> +      <Img src={props.item.image} />
хуитем

2018-01-06 15:42 UTC, evgenyrodionov commented on src/Destinations/Card.js
> +      <Img src={props.item.image} />
читай частые ошибки

2018-01-06 15:42 UTC, evgenyrodionov commented on src/Destinations/index.js
> +  const items = [
зачем это в функции держать?

2018-01-06 15:42 UTC, evgenyrodionov commented on src/Destinations/index.js
> +  const listItems = items.map((item, index) => (
хуитемс

2018-01-07 22:25 UTC, imevro requested changes

2018-01-07 22:25 UTC, evgenyrodionov commented on src/Destinations/Card.js
> +const CardBody = styled.div`
зачем в файле кард столько префиксов кард?

2018-01-07 22:25 UTC, evgenyrodionov commented on src/index.css
> +    display: none;
нахуя?

https://github.com/evgenyrodionov/flexboxgrid2/releases/tag/7.0.0-alpha7

2018-01-07 22:25 UTC, evgenyrodionov commented on src/Destinations/index.js
> +        <Col xs={12}>
зачем колонки для заголовков? просто в контейнер положи и всё

2018-01-09 00:44 UTC, merged