Feat/homes page
rrrds/airbnb-demo-frontend pull request #2
Opened 2018-01-11 08:11 UTC by rrrds

live demo: https://build-axbrtukppu.now.sh

2018-01-11 19:44 UTC, evgenyrodionov commented
Поставь react-helmet и настрой нормальные тайтлы
![image](https://user-images.githubusercontent.com/775692/34843863-c64dbb02-f720-11e7-9455-e17837fbb590.png)

---

У хедера ссылки в кучку, а у карточек в Explore слишком тонкий шрифт
![image](https://user-images.githubusercontent.com/775692/34843876-cf83ae8e-f720-11e7-9428-8834aa2b40c8.png)

---

Сожрало
![image](https://user-images.githubusercontent.com/775692/34843903-e00a2c74-f720-11e7-80a4-be0e90f93e40.png)

---

Это чё с иконкой ваще?
![image](https://user-images.githubusercontent.com/775692/34843920-e9dfb908-f720-11e7-9e22-f806e4fa5949.png)

---

У этих кнопок нет `cursor: pointer` при ховере, да и вообще, это кнопки?
![image](https://user-images.githubusercontent.com/775692/34843942-fa8ff7ae-f720-11e7-855e-f97bac315c74.png)

2018-01-11 19:58 UTC, imevro requested changes

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Header/Search.js
> +  return <Input placeholder="Try 'Miami'" />;
читай частые ошибки первого этапа про компоненты-прокладки

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Header/index.js
> +          <MainWrapper>
пиздец у тебя врапперов, ты сам не путаешься в этих водопадах вложенных компонентов?

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Header/index.js
> +          <MainWrapper>
упрощай

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Homes/Filters.js
> +const PickerButton = styled.a`
button = a?

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Homes/Paginator.js
> +        <Col xs={12}>
зачем тут сетка?

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Homes/index.js
> +const homesRows = homes
это чё ваще? в сетке можно напихать сколько угодно элементов, не ограничиваясь 12 колонками, поэтому ничего не сломается

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Homes/index.js
> +const WebMap = styled.div`
чё за вебмап?

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Landing/Explore/Card.js
> +    <Card to={props.linkTo}>
что мешает сделать props.to?

2018-01-11 19:58 UTC, evgenyrodionov commented on src/Landing/Explore/index.js
> +    <Card text={exp.name} image={exp.image} linkTo={exp.link} />
`linkTo={link}` чтобы внутри передать в проп `to`? Тебе не кажется что ты щас одну сущность на три разделил?

2018-01-13 10:07 UTC, evgenyrodionov commented
С картинками мыло, тут опечатка
![image](https://user-images.githubusercontent.com/775692/34905068-5660ef4c-f862-11e7-8557-d433342c76f3.png)

Шрифт крупнее чем надо
![image](https://user-images.githubusercontent.com/775692/34905071-5e3c1a52-f862-11e7-84bd-be2ec39a1f23.png)

Всё слиплось в футере
![image](https://user-images.githubusercontent.com/775692/34905073-654d6b98-f862-11e7-8558-14ae69b56683.png)

У кнопок нет cursor pointer
 
При клике за пределами открытого фильтра он не закрывается

Держи тире — вместо дефиса
![image](https://user-images.githubusercontent.com/775692/34905077-7e1573be-f862-11e7-843b-b10517931d8b.png)

2018-01-13 10:10 UTC, imevro requested changes
не код, а сплошные врапперы, чертовски сложно читать когда столько вложенных вещей

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Header/Nav.js
> +  margin: 0 0.8vw;
viewport width? зачем?

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Header/index.js
> +          <MainWrapper>
ну и чё?

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +import x from "./x.svg";
x?

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +const FILTER_ID = "dates";
ЗАЧЕМ_ТАК_ОРАТЬ

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +const FILTER_ID = "dates";
camelCase и всё

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +export default props => {
1) читай частые ошибки
2) ебать ты нахуевертил, упрощай

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +  > small {
нет

2018-01-13 10:10 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +          : {
тут какая-то территория убийства

2018-01-21 08:00 UTC, imevro requested changes

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  return currentFilterId === filterId;
а почему ты этим занимаешься здесь, да ещё в отдельной функции? вынеси в родителя и передавай сразу результат проверки как проп

`isActive={currentFilterId === "dates"}`

ну и опять же, ебучие префиксы и постфиксы Filter когда ты уже в фильтре

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +          <ActionRow>
почему это вообще роу, если оно идёт параллельно предыдущему блоку?

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    : window.matchMedia("(min-width: 768px)").matches ? 1 : 4;
фу, вложенные тернарники, отвратительно

раздели на нормальные ифы

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    this.setState({
зачем тебе дублировать пропы в стейт?

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +      startDate: this.state.startDate,
реально, ради объекта с двумя полями ты завёл отдельный метод?

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +      e
зачем ты эвент передаешь как коллбек? Не понимаю

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  getFilterButtonText() {
написано в частых ошибках — вынеси этот форматтер за пределы класса, ему нет места тут

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    const picker = (
Если это компонент, то почему не PascalCase?

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +            {({ openPortal, closePortal, isOpen, portal }) =>
разнеси всю эту еболу на несколько компонентов и в тернарнике у тебя будет кроткое `isMobile ? <Mobile /> : <Desktop />`

нейминг для примера дан, это раз; у нас нет терминологии мобайл/десктоп, это два

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +              {props.filter}
фильтр что?

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +              onClick={e => this.onDecrase("adults", e)}
decrease, у тебя опечатка

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +        <TypeRow>
что за тайп роу?

2018-01-21 08:00 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +            Infants<NameAside>Under 2</NameAside>
а если будет не асайд? зачем ты так именуешь? назови просто Description

2018-01-22 14:36 UTC, imevro requested changes

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +        formatButtonText(endDate, "Check out")
es template strings используй

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  } else if (window.matchMedia("(min-width: 768px)").matches) {
зачем тут else? просто иф второй ставь

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +  } else {
как и тут

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +            e
так зачем ты эвент вообще туда передаешь? не понимаю

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/Popup.js
> +          props.onClose();
а зачем ты тут создал ещё одну функцию? передал бы ссылкой и всё

`handleClickOutside={props.onClose}`

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/Portal.js
> +const Title = styled.div`
тайтл = див?

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/Portal.js
> +                    closePortal();
да вынеси в отдельные функции, чё ты экономишь константы? некрасиво же смотрится

2018-01-22 14:36 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/index.js
> +            filterComponent={props.filterComponent}
чем чилдрен не угодил?

2018-01-22 15:40 UTC, rrrds commented on src/Homes/Filters/Dates.js
> +            e
Где то в документации попалось. Наверное это был input.

2018-01-22 19:55 UTC, imevro requested changes

2018-01-22 19:55 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/index.js
> +            {props.filterComponent}
а тут почему не чилдрен?

2018-01-22 20:27 UTC, rrrds commented
в дропдаун передается сам фильтр и кнопка, через пропсы. Дропдаун решает что показать: попап или портал. И ниже передает только фильтр в попап или портал.
Привел все к единому стилю - передаю через пропсы

2018-01-22 23:12 UTC, imevro requested changes

2018-01-22 23:12 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/ResponsivePopup.js
> +    props.isActive &&
сделай нормальными if-return 

```js
if (x) return <div>1</div>
if (y) return <div>2</div>
```

2018-01-22 23:24 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown/ResponsivePopup.js
> +  return null;
можно и без этого

2018-01-22 23:24 UTC, imevro approved these changes

2018-01-22 23:24 UTC, merged