Feat/filters
rrrds/airbnb-demo-frontend pull request #4
Opened 2018-01-26 08:29 UTC by rrrds

2018-01-26 13:19 UTC, evgenyrodionov commented
а деплой где?

2018-01-26 13:33 UTC, rrrds commented
https://dem0-airbnb.now.sh/

2018-01-26 16:28 UTC, evgenyrodionov commented
Чё с кнопками? Чё с шрифтами?
![image](https://user-images.githubusercontent.com/775692/35449760-fb6f5bba-02ce-11e8-8d10-e8d751478f87.png)

Тут тоже шрифты левые
![image](https://user-images.githubusercontent.com/775692/35449776-07bb640e-02cf-11e8-9c0f-3670313bb25c.png)

И тут тоже шрифты
![image](https://user-images.githubusercontent.com/775692/35449793-11ce9a06-02cf-11e8-9d05-018581a613ce.png)

2018-01-26 16:28 UTC, evgenyrodionov commented
Гигантские проблемы со шрифтами

2018-01-26 16:30 UTC, imevro requested changes

2018-01-26 16:30 UTC, evgenyrodionov commented on src/Homes/Filters/InstantBook/index.js
> +  &.on .switch-toggle {
а почему тут классы пошли?

2018-01-26 16:30 UTC, evgenyrodionov commented on src/Homes/Filters/Price/index.js
> +  <div
почему не кнопка?

2018-01-26 16:30 UTC, evgenyrodionov commented on src/Homes/Filters/Price/index.js
> +      height: 32,
не понял, а почему не СК, а инлайн-стили?

2018-01-27 12:58 UTC, evgenyrodionov commented
ГДЕ ДЕПЛОЙ?

2018-01-27 14:49 UTC, rrrds commented
https://dem0-airbnb.now.sh/

2018-01-27 20:27 UTC, rrrds commented
https://dem0-airbnb.now.sh 
или https://build-wfubdgxrsn.now.sh

2018-01-28 18:58 UTC, evgenyrodionov commented
Ты решил побыть сам дизайнером? Открывай макет и переделывай
![image](https://user-images.githubusercontent.com/775692/35485869-599914e4-0476-11e8-82ba-24bcd46236f5.png)

2018-01-28 19:00 UTC, imevro requested changes

2018-01-28 19:00 UTC, evgenyrodionov commented on src/Homes/Filters/Amenities/index.js
> +  &.checked {
есть пропы

2018-01-28 19:00 UTC, evgenyrodionov commented on src/Homes/Filters/Amenities/index.js
> +export default class Amenities extends React.Component {
зачем тут класс? ты используешь стейт или лайфсайкл?

2018-01-29 19:20 UTC, rrrds commented
https://dem0-airbnb.now.sh/
https://build-mlfcugidgd.now.sh

2018-01-29 21:06 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534345-483b9916-0551-11e8-9e8d-3e603b055fbe.png)
![image](https://user-images.githubusercontent.com/775692/35534374-65e4262c-0551-11e8-8797-db742e7449e5.png)

2018-01-29 21:07 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534395-71e16264-0551-11e8-877b-d1cdd8561ec8.png)
![image](https://user-images.githubusercontent.com/775692/35534412-82bc984c-0551-11e8-87e4-388c17d87970.png)

2018-01-29 21:07 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534428-8d9ae30e-0551-11e8-909f-3757306ae40e.png)
![image](https://user-images.githubusercontent.com/775692/35534433-90bcab9e-0551-11e8-8e5b-6a3fa635bf88.png)

2018-01-29 21:07 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534445-9ae2065a-0551-11e8-90c8-31e8e2a34a89.png)
![image](https://user-images.githubusercontent.com/775692/35534450-9e1bca72-0551-11e8-8db8-1f8cd004e075.png)

2018-01-29 21:08 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534465-a6891836-0551-11e8-8c5c-b051bd07407e.png)
![image](https://user-images.githubusercontent.com/775692/35534475-ac5e058c-0551-11e8-81a9-0aba43442681.png)

2018-01-29 21:15 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534775-97ea1c16-0552-11e8-8154-9a30bb76c817.png)
![image](https://user-images.githubusercontent.com/775692/35534804-ad688a50-0552-11e8-9bce-f5a86ce61bb2.png)

2018-01-29 21:16 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35534839-bfadcaae-0552-11e8-890b-8e67331b26b3.png)
![image](https://user-images.githubusercontent.com/775692/35534850-cbd7788e-0552-11e8-9000-33c6123957d5.png)

2018-01-30 01:21 UTC, rrrds commented
https://build-zwpblogqkf.now.sh

2018-01-30 08:11 UTC, imevro requested changes

2018-01-30 08:11 UTC, evgenyrodionov commented on src/Homes/index.js
> +  width: -o-calc(50% - 992px / 2 + 992px * 0.333);
в СК есть автопрефиксер, нет нужды это руками расставлять

2018-01-30 09:13 UTC, rrrds commented
https://build-uyxuyfnvwo.now.sh

2018-02-01 16:01 UTC, imevro approved these changes

2018-02-01 16:01 UTC, merged