feat/api
rrrds/airbnb-demo-frontend pull request #6
Opened 2018-02-02 08:30 UTC by rrrds

https://build-hgagdaroxh.now.sh/

2018-02-03 10:52 UTC, imevro requested changes
не понял зачем в стулед.джс напихивать хелперов, лень файл helpers.js создать?

2018-02-03 10:52 UTC, evgenyrodionov commented on src/Homes/styled.js
> +const formatKind = kind =>
сделай обычный объект

2018-02-03 10:52 UTC, evgenyrodionov commented on src/Homes/styled.js
> +const formatHost = (reviewsCount, isSuperhost) => {
а что это забыло в стайлед вообще?

2018-02-03 10:52 UTC, evgenyrodionov commented on src/Landing/Homes/index.js
> +            <HomesList homes={this.state.homes} xs={8} md={5} lg={4} />
ты передаешь что контейнер должен занимать 5 колонок на мд? Сомневаюсь, что так, а следовательно это вообще не очевидно, что речь про карточки.

у тебя дырявая неудобная абстракция, исправляй

2018-02-03 20:49 UTC, rrrds commented
https://build-etfwqjcrsv.now.sh

2018-02-04 15:38 UTC, imevro requested changes

2018-02-04 15:38 UTC, evgenyrodionov commented on src/Homes/helpers.js
> +    return `${reviewsCount} · Superhost`;
как суперхост соотносится с количеством отзывов?

2018-02-04 15:38 UTC, evgenyrodionov commented on src/Homes/helpers.js
> +  type: kindToText[inData.kind],
а зачем ты в сырые данные кидаешь отформатированные? если тебе нужно будет делать i18n, что делать будешь? это нелогично, в рендере решай что делать с сырьём

2018-02-05 14:59 UTC, merged